In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [2]:
# csv
phne_022344_csv = pd.read_csv('data/phones_data_20250729_022344.csv')
phne_181901_csv = pd.read_csv('data/phones_data_20250729_181901.csv')

Copy the Raw file into 'df'

In [3]:
df = phne_181901_csv.copy()

In [4]:
df.shape

(4144, 86)

In [5]:
df.head(5)

,brand,model,device_type,release_date,status,architecture,aspect_ratio,audio_jack,battery_capacity,battery_placement,battery_type,bezel_less_display,bluetooth,brightness,chipset,colors,cpu,cpu_cores,detail_url,display_type,edge,expandable_memory,fabrication,face_unlock,features,gprs,gps,gpu,height,image_url,internal_storage,ip_rating,loudspeaker,made_by,network,notch,operating_system,os_version,pixel_density,price_official,price_old,price_savings,price_unofficial,price_updated,price_variants,primary_camera_autofocus,primary_camera_features,primary_camera_flash,primary_camera_image_resolution,primary_camera_resolution,primary_camera_settings,primary_camera_setup,primary_camera_shooting_modes,primary_camera_video_fps,primary_camera_video_recording,primary_camera_zoom,quick_charging,ram,ram_type,refresh_rate,resolution,ruggedness,scraped_at,screen_protection,screen_size,screen_to_body_ratio,selfie_camera_resolution,selfie_camera_setup,sensors,sim_size,sim_slot,speed,storage_type,thickness,touch_screen,usb,usb_otg,usb_type_c,user_interface,video,volte,waterproof,weight,width,wifi_hotspot,wlan
0,Oppo,K13 Turbo Pro (512GB),Smartphone,25 July 2025,Available,64 bit,19.5:9,USB Type-C,Li-Po 7000mAh,NaN,NaN,NaN,v5.4,1600 nits,Qualcomm SM8735 Snapdragon 8s Gen 4,"Black Warrior, Purple No. 1, Knight Silver",Octa-core (1x3.21 GHz Cortex-X4 & 3x3.0 GHz Co...,8 Cores,https://www.mobiledokan.com/mobile/oppo-k13-tu...,AMOLED,Available,NaN,4 nm,Yes,"Accelerometer, gyro, proximity, compass",Available,"Yes with A-GPS, Glonass",Adreno 825,162.8 mm,https://www.mobiledokan.com/media/oppo-k13-tur...,512GB,IP68/IP69,Yes,NaN,"2G, 3G, 4G, 5G",Punch-hole,Android v15,v15,453 ppi,NaN,NaN,NaN,"56,000","July 28, 2025","[{'variant': '12GB+512GB CN', 'price': '56,000...",NaN,NaN,NaN,NaN,50+2MP,NaN,NaN,NaN,NaN,NaN,NaN,"80W wired, 13.5W PD, 44W UFCS, 33W PPS",12GB,LPDDR5X,120 Hz,"50 MP, f/1.8, Wide Angle, Primary Camera, 2 MP...",Dust proof,2025-07-29T17:02:23.596376,Gorilla Glass,6.8''1280x2800p,89.8%,NaN,NaN,NaN,"SIM1: Nano, SIM2: Nano","Dual SIM, GSM+GSM","HSPA, LTE, 5G",UFS 4.0,7.3 mm,"Capacitive Touchscreen, Multi-touch","Mass storage device, USB charging",Yes,USB Type-C 2.0,ColorOS 15,"4K@30/60fps, 1080p@30fps",Yes,Water resistant (up to 2m for 30 min),208 grams,77.2 mm,NaN,"Wi-Fi 7 (802.11 a/b/g/n/ac/be/ax) 5GHz 6GHz, MIMO"
1,Oppo,K13 Turbo (512GB),Smartphone,25 July 2025,Available,64 bit,19.5:9,USB Type-C,Li-Po 7000mAh,NaN,NaN,NaN,v5.4,1600 nits,Mediatek Dimensity 8450,"Black Warrior, Purple No. 1, Knight White",Octa-core (1x3.25 GHz Cortex-A725 & 3x3.0 GHz ...,8 Cores,https://www.mobiledokan.com/mobile/oppo-k13-tu...,AMOLED,Available,NaN,4 nm,Yes,"Accelerometer, gyro, proximity, compass",Available,"Yes with A-GPS, Glonass",Mali-G720 MC7,162.8 mm,https://www.mobiledokan.com/media/oppo-k13-tur...,512GB,IP68/IP69,Yes,NaN,"2G, 3G, 4G, 5G",Punch-hole,Android v15,v15,453 ppi,NaN,NaN,NaN,"52,000","July 28, 2025","[{'variant': '12GB+512GB CN', 'price': '52,000...",NaN,NaN,NaN,NaN,50+2MP,NaN,NaN,NaN,NaN,NaN,NaN,"80W wired, 13.5W PD, 44W UFCS, 33W PPS",12GB,LPDDR5X,120 Hz,"50 MP, f/1.8, Wide Angle, Primary Camera, 2 MP...",Dust proof,2025-07-29T17:02:24.734934,Gorilla Glass,6.8''1280x2800p,89.8%,NaN,NaN,NaN,"SIM1: Nano, SIM2: Nano","Dual SIM, GSM+GSM","HSPA, LTE, 5G",UFS 3.1,7.3 mm,"Capacitive Touchscreen, Multi-touch","Mass storage device, USB charging",Yes,USB Type-C 2.0,ColorOS 15,"4K@30/60fps, 1080p@30fps",Yes,Water resistant (up to 2m for 30 min),207 grams,77.2 mm,NaN,"Wi-Fi 6 (802.11 a/b/g/n/ac/ax) 5GHz, MIMO"
2,Vivo,Y400,Smartphone,Not announced yet,Rumored,64 bit,NaN,USB Type-C,Li-Po 6000mAh,NaN,NaN,NaN,v5.0,NaN,Qualcomm SM6225 Snapdragon 685,Green; other colors,Octa-core (2x2.2 GHz Cortex-A78 & 6x1.95 GHz C...,8 Cores,https://www.mobiledokan.com/mobile/vivo-y400,AMOLED,Available,NaN,6 nm,Yes,"Accelerometer, gyro, proximity, compass",Available,"Yes with A-GPS, Glonass",Adreno 613,NaN,https://www.mobiledokan.com/media/vivo-y400-gr...,128GB,IP68/IP69,Yes,NaN,"2G, 3G, 4G",Punch-hole,Android v15,v15,NaN,NaN,NaN,NaN,NaN,"July 27, 2025",[],NaN,NaN,NaN,NaN,50+2MP,NaN,NaN,NaN,NaN,NaN,NaN,44W wired,8GB,NaN,120 Hz,"50 MP, f/1.8, Wide Angle, Primary Camera, 2 MP...",Dust proof,2025-07-29T17:02:25.641000,Gorilla Glass,6.67''1080x2400p,NaN,NaN,NaN,NaN,"SIM1: Nano, SIM2: Nano","Dual SIM, GSM+GSM","HSPA, LTE",NaN,NaN,"Capacitive Touchscreen, Multi-touch","Mass storage device, USB charging",Yes,USB Type-C 2.0,Funtouch 15,"1080p@30fps, gyro-EIS",Yes,Water resistant (up to 1.5m for 30 min),NaN,NaN,NaN,Wi-Fi 5 (802.11 a/b/g/n/ac) 5GHz
3,Infinix,Hot 60 Pro Plus (256GB),Smartphone,25 July 2025,Available,64 bit,20:9,3.5 mm,Li-Po 5160mAh,NaN,NaN,NaN,v5.4,4500 nits,Mediatek Helio G200,"Sleek Black, Titanium Silver, Coral Tides, Mis...",Octa-core (2x2.2 GHz Cortex-A76 & 6x2.0 GHz Co...,8 Cores,https://www.mobiledokan.com/mobile/infinix-hot...,AMOLED,Available,NaN,6 nm,Yes,"Accelerometer, proximity, compass",Available,Yes with A-GPS,Mali-G57 MC2 (1.1GHz),164 mm,https://www.mobiledokan.com/media/infinix-hot-...,256GB,IP65,Yes,NaN,"2G, 3G, 4G",Punch-hole,Android v15,v15,440 ppi,"23,999",NaN,NaN,NaN,"July 25, 2025","[{'variant': '8GB+256GB', 'price': '23,999'}, ...",NaN,NaN,NaN,NaN,50MP,NaN,NaN,NaN,NaN,NaN,NaN,"45W wired, 50% in 22 min",8GB,NaN,144 Hz,"50 MP, Wide Angle, Primary Camera",Dust proof,2025-07-29T17:02:26.728739,Corning Gorilla Glass 7i,6.78''1224x2720p,89.3%,NaN,NaN,NaN,"SIM1: Nano, SIM2: Nano","Dual SIM, GSM+GSM","HSPA, LTE",UFS 2.2,6 mm,"Capacitive Touchscreen, Multi-touch","Mass storage device, USB charging",Yes,USB Type-C 2.0,XOS 15.1,"1440p@30fps, 1080p@30/60fps",Yes,Splash proof,155 grams,75.8 mm,NaN,Wi-Fi 5 (802.11 a/b/g/n/ac) 5GHz
4,Realme,Note 70T,Smartphone,Exp. 31 July 2025,Upcoming,64 bit,20:9,3.5 mm,Li-Po 6000mAh,NaN,NaN,NaN,v5.4,NaN,Unisoc T7250,"Gold, Black",Octa-core (2x1.8 GHz Cortex-A75 & 6x1.6 GHz Co...,8 Cores,https://www.mobiledokan.com/mobile/realme-note...,IPS LCD,Available,NaN,12 nm,Yes,"Accelerometer, proximity, compass",Available,"Yes with A-GPS, Glonass",Mali-G57 MP1,167.2 mm,https://www.mobiledokan.com/media/realme-note-...,128GB,IP54,Yes,NaN,"2G, 3G, 4G",Punch-hole,Android v15,v15,260 ppi,NaN,NaN,NaN,NaN,"July 24, 2025",[],NaN,NaN,NaN,NaN,50+13MP,NaN,NaN,NaN,NaN,NaN,NaN,15W wired,4GB,NaN,90 Hz,"50 MP, f/2.2, Wide Angle, Primary Camera, 13 M...",Dust proof,2025-07-29T17:02:27.622402,Panda Glass,6.74''720x1600p,85.6%,NaN,NaN,NaN,"SIM1: Nano, SIM2: Nano","Dual SIM, GSM+GSM","HSPA, LTE",NaN,7.9 mm,"Capacitive Touchscreen, Multi-touch","Mass storage device, USB charging",Yes,USB Type-C 2.0,Realme UI 5.0,1080p@30fps,Yes,Splash proof,201 grams,76.6 mm,NaN,Wi-Fi 5 (802.11 a/b/g/n/ac) 5GHz

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4144 entries, 0 to 4143
Data columns (total 86 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   brand                            4144 non-null   str
 1   model                            4144 non-null   str
 2   device_type                      4142 non-null   str
 3   release_date                     4142 non-null   str
 4   status                           4137 non-null   str
 5   architecture                     3712 non-null   str
 6   aspect_ratio                     3225 non-null   str
 7   audio_jack                       4019 non-null   str
 8   battery_capacity                 4142 non-null   str
 9   battery_placement                0 non-null      float64
 10  battery_type                     0 non-null      float64
 11  bezel_less_display               0 non-null      float64
 12  bluetooth                        4137 non-null   str
 13  brightness                       1811 non-null   str
 14  chipset                          3788 non-null   str
 15  colors                           4110 non-null   str
 16  cpu                              4080 non-null   str
 17  cpu_cores                        4001 non-null   str
 18  detail_url                       4144 non-null   str
 19  display_type                     4141 non-null   str
 20  edge                             4105 non-null   str
 21  expandable_memory                2482 non-null   str
 22  fabrication                      3287 non-null   str
 23  face_unlock                      3032 non-null   str
 24  features                         4079 non-null   str
 25  gprs                             4113 non-null   str
 26  gps                              4045 non-null   str
 27  gpu                              3967 non-null   str
 28  height                           3942 non-null   str
 29  image_url                        4142 non-null   str
 30  internal_storage                 4133 non-null   str
 31  ip_rating                        1363 non-null   str
 32  loudspeaker                      4138 non-null   str
 33  made_by                          0 non-null      float64
 34  network                          4142 non-null   str
 35  notch                            3802 non-null   str
 36  operating_system                 4138 non-null   str
 37  os_version                       4083 non-null   str
 38  pixel_density                    3864 non-null   str
 39  price_official                   2502 non-null   str
 40  price_old                        200 non-null    str
 41  price_savings                    200 non-null    str
 42  price_unofficial                 1575 non-null   str
 43  price_updated                    4142 non-null   str
 44  price_variants                   4144 non-null   str
 45  primary_camera_autofocus         0 non-null      float64
 46  primary_camera_features          0 non-null      float64
 47  primary_camera_flash             0 non-null      float64
 48  primary_camera_image_resolution  0 non-null      float64
 49  primary_camera_resolution        4138 non-null   str
 50  primary_camera_settings          0 non-null      float64
 51  primary_camera_setup             0 non-null      float64
 52  primary_camera_shooting_modes    0 non-null      float64
 53  primary_camera_video_fps         0 non-null      float64
 54  primary_camera_video_recording   0 non-null      float64
 55  primary_camera_zoom              0 non-null      float64
 56  quick_charging                   2818 non-null   str
 57  ram                              4108 non-null   str
 58  ram_type                         2434 non-null   str
 59  refresh_rate                     2914 non-null   str
 60  resolution                       4142 non-null   str
 61  ruggedness                       1326 non-null   str
 62  scraped_at                       4144 non-null   str
 63  screen_protection                4057 non-null   str
 64  screen_size                      4142 non-null   str
 65  screen_to_body_ratio             3478 non-null   str
 66  selfie_camera_resolution         0 non-null      float64
 67  selfie_camera_setup              0 non-null      float64
 68  sensors                          0 non-null      float64
 69  sim_size                         3995 non-null   str
 70  sim_slot                         4138 non-null   str
 71  speed                            4019 non-null   str
 72  storage_type                     2402 non-null   str
 73  thickness                        3972 non-null   str
 74  touch_screen                     4093 non-null   str
 75  usb                              4098 non-null   str
 76  usb_otg                          3209 non-null   str
 77  usb_type_c                       2544 non-null   str
 78  user_interface                   2258 non-null   str
 79  video                            4043 non-null   str
 80  volte                            3653 non-null   str
 81  waterproof                       1540 non-null   str
 82  weight                           3724 non-null   str
 83  width                            3942 non-null   str
 84  wifi_hotspot                     0 non-null      float64
 85  wlan                             4097 non-null   str
dtypes: float64(18), str(68)
memory usage: 6.5 MB

In [7]:
# checking missing value
print(df.isna().sum().sort_values(ascending=False))

print('\n=== missing value in percentage ====')
missing = (df.isna().mean()*100).round(1).sort_values(ascending=False)
print(missing)

made_by                            4144
battery_placement                  4144
primary_camera_autofocus           4144
primary_camera_features            4144
primary_camera_flash               4144
sensors                            4144
primary_camera_image_resolution    4144
bezel_less_display                 4144
selfie_camera_resolution           4144
battery_type                       4144
primary_camera_settings            4144
primary_camera_setup               4144
primary_camera_shooting_modes      4144
primary_camera_video_fps           4144
primary_camera_video_recording     4144
primary_camera_zoom                4144
wifi_hotspot                       4144
selfie_camera_setup                4144
price_savings                      3944
price_old                          3944
ruggedness                         2818
ip_rating                          2781
waterproof                         2604
price_unofficial                   2569
brightness                         2333
user_interface                     1886
storage_type                       1742
ram_type                           1710
expandable_memory                  1662
price_official                     1642
usb_type_c                         1600
quick_charging                     1326
refresh_rate                       1230
face_unlock                        1112
usb_otg                             935
aspect_ratio                        919
fabrication                         857
screen_to_body_ratio                666
volte                               491
architecture                        432
weight                              420
chipset                             356
notch                               342
pixel_density                       280
width                               202
height                              202
gpu                                 177
thickness                           172
sim_size                            149
cpu_cores                           143
audio_jack                          125
speed                               125
video                               101
gps                                  99
screen_protection                    87
features                             65
cpu                                  64
os_version                           61
touch_screen                         51
wlan                                 47
usb                                  46
edge                                 39
ram                                  36
colors                               34
gprs                                 31
internal_storage                     11
bluetooth                             7
status                                7
primary_camera_resolution             6
loudspeaker                           6
sim_slot                              6
operating_system                      6
display_type                          3
price_updated                         2
screen_size                           2
resolution                            2
network                               2
image_url                             2
battery_capacity                      2
release_date                          2
device_type                           2
scraped_at                            0
price_variants                        0
model                                 0
detail_url                            0
brand                                 0
dtype: int64

=== missing value in percentage ====
primary_camera_settings            100.0
bezel_less_display                 100.0
selfie_camera_setup                100.0
primary_camera_features            100.0
primary_camera_image_resolution    100.0
made_by                            100.0
sensors                            100.0
primary_camera_setup               100.0
primary_camera_autofocus           100.0
primary_camera_shooting_modes      100.0
battery_type                       100.0
primary_camera_flash               100.0
battery_placement                  100.0
primary_camera_video_fps           100.0
primary_camera_video_recording     100.0
primary_camera_zoom                100.0
wifi_hotspot                       100.0
selfie_camera_resolution           100.0
price_savings                       95.2
price_old                           95.2
ruggedness                          68.0
ip_rating                           67.1
waterproof                          62.8
price_unofficial                    62.0
brightness                          56.3
user_interface                      45.5
storage_type                        42.0
ram_type                            41.3
expandable_memory                   40.1
price_official                      39.6
usb_type_c                          38.6
quick_charging                      32.0
refresh_rate                        29.7
face_unlock                         26.8
usb_otg                             22.6
aspect_ratio                        22.2
fabrication                         20.7
screen_to_body_ratio                16.1
volte                               11.8
architecture                        10.4
weight                              10.1
chipset                              8.6
notch                                8.3
pixel_density                        6.8
height                               4.9
width                                4.9
gpu                                  4.3
thickness                            4.2
sim_size                             3.6
cpu_cores                            3.5
audio_jack                           3.0
speed                                3.0
video                                2.4
gps                                  2.4
screen_protection                    2.1
features                             1.6
cpu                                  1.5
os_version                           1.5
touch_screen                         1.2
usb                                  1.1
wlan                                 1.1
ram                                  0.9
edge                                 0.9
colors                               0.8
gprs                                 0.7
internal_storage                     0.3
bluetooth                            0.2
status                               0.2
primary_camera_resolution            0.1
loudspeaker                          0.1
display_type                         0.1
sim_slot                             0.1
operating_system                     0.1
brand                                0.0
screen_size                          0.0
scraped_at                           0.0
resolution                           0.0
price_variants                       0.0
model                                0.0
network                              0.0
image_url                            0.0
detail_url                           0.0
battery_capacity                     0.0
release_date                         0.0
device_type                          0.0
price_updated                        0.0
dtype: float64

In [8]:
df.duplicated(['detail_url']).sum()

np.int64(1)

### Cleaning Data

In [9]:
# dropping column that are more than 90% empty

empty_col = missing[missing > 90].index
df= df.drop(columns=empty_col)
print('dropped', len(empty_col), 'empty_col')

dropped 20 empty_col

In [10]:
# removing duplicate

df=df.drop_duplicates(subset='detail_url')

In [11]:
df.head(10)

,brand,model,device_type,release_date,status,architecture,aspect_ratio,audio_jack,battery_capacity,bluetooth,brightness,chipset,colors,cpu,cpu_cores,detail_url,display_type,edge,expandable_memory,fabrication,face_unlock,features,gprs,gps,gpu,height,image_url,internal_storage,ip_rating,loudspeaker,network,notch,operating_system,os_version,pixel_density,price_official,price_unofficial,price_updated,price_variants,primary_camera_resolution,quick_charging,ram,ram_type,refresh_rate,resolution,ruggedness,scraped_at,screen_protection,screen_size,screen_to_body_ratio,sim_size,sim_slot,speed,storage_type,thickness,touch_screen,usb,usb_otg,usb_type_c,user_interface,video,volte,waterproof,weight,width,wlan
0,Oppo,K13 Turbo Pro (512GB),Smartphone,25 July 2025,Available,64 bit,19.5:9,USB Type-C,Li-Po 7000mAh,v5.4,1600 nits,Qualcomm SM8735 Snapdragon 8s Gen 4,"Black Warrior, Purple No. 1, Knight Silver",Octa-core (1x3.21 GHz Cortex-X4 & 3x3.0 GHz Co...,8 Cores,https://www.mobiledokan.com/mobile/oppo-k13-tu...,AMOLED,Available,NaN,4 nm,Yes,"Accelerometer, gyro, proximity, compass",Available,"Yes with A-GPS, Glonass",Adreno 825,162.8 mm,https://www.mobiledokan.com/media/oppo-k13-tur...,512GB,IP68/IP69,Yes,"2G, 3G, 4G, 5G",Punch-hole,Android v15,v15,453 ppi,NaN,"56,000","July 28, 2025","[{'variant': '12GB+512GB CN', 'price': '56,000...",50+2MP,"80W wired, 13.5W PD, 44W UFCS, 33W PPS",12GB,LPDDR5X,120 Hz,"50 MP, f/1.8, Wide Angle, Primary Camera, 2 MP...",Dust proof,2025-07-29T17:02:23.596376,Gorilla Glass,6.8''1280x2800p,89.8%,"SIM1: Nano, SIM2: Nano","Dual SIM, GSM+GSM","HSPA, LTE, 5G",UFS 4.0,7.3 mm,"Capacitive Touchscreen, Multi-touch","Mass storage device, USB charging",Yes,USB Type-C 2.0,ColorOS 15,"4K@30/60fps, 1080p@30fps",Yes,Water resistant (up to 2m for 30 min),208 grams,77.2 mm,"Wi-Fi 7 (802.11 a/b/g/n/ac/be/ax) 5GHz 6GHz, MIMO"
1,Oppo,K13 Turbo (512GB),Smartphone,25 July 2025,Available,64 bit,19.5:9,USB Type-C,Li-Po 7000mAh,v5.4,1600 nits,Mediatek Dimensity 8450,"Black Warrior, Purple No. 1, Knight White",Octa-core (1x3.25 GHz Cortex-A725 & 3x3.0 GHz ...,8 Cores,https://www.mobiledokan.com/mobile/oppo-k13-tu...,AMOLED,Available,NaN,4 nm,Yes,"Accelerometer, gyro, proximity, compass",Available,"Yes with A-GPS, Glonass",Mali-G720 MC7,162.8 mm,https://www.mobiledokan.com/media/oppo-k13-tur...,512GB,IP68/IP69,Yes,"2G, 3G, 4G, 5G",Punch-hole,Android v15,v15,453 ppi,NaN,"52,000","July 28, 2025","[{'variant': '12GB+512GB CN', 'price': '52,000...",50+2MP,"80W wired, 13.5W PD, 44W UFCS, 33W PPS",12GB,LPDDR5X,120 Hz,"50 MP, f/1.8, Wide Angle, Primary Camera, 2 MP...",Dust proof,2025-07-29T17:02:24.734934,Gorilla Glass,6.8''1280x2800p,89.8%,"SIM1: Nano, SIM2: Nano","Dual SIM, GSM+GSM","HSPA, LTE, 5G",UFS 3.1,7.3 mm,"Capacitive Touchscreen, Multi-touch","Mass storage device, USB charging",Yes,USB Type-C 2.0,ColorOS 15,"4K@30/60fps, 1080p@30fps",Yes,Water resistant (up to 2m for 30 min),207 grams,77.2 mm,"Wi-Fi 6 (802.11 a/b/g/n/ac/ax) 5GHz, MIMO"
2,Vivo,Y400,Smartphone,Not announced yet,Rumored,64 bit,NaN,USB Type-C,Li-Po 6000mAh,v5.0,NaN,Qualcomm SM6225 Snapdragon 685,Green; other colors,Octa-core (2x2.2 GHz Cortex-A78 & 6x1.95 GHz C...,8 Cores,https://www.mobiledokan.com/mobile/vivo-y400,AMOLED,Available,NaN,6 nm,Yes,"Accelerometer, gyro, proximity, compass",Available,"Yes with A-GPS, Glonass",Adreno 613,NaN,https://www.mobiledokan.com/media/vivo-y400-gr...,128GB,IP68/IP69,Yes,"2G, 3G, 4G",Punch-hole,Android v15,v15,NaN,NaN,NaN,"July 27, 2025",[],50+2MP,44W wired,8GB,NaN,120 Hz,"50 MP, f/1.8, Wide Angle, Primary Camera, 2 MP...",Dust proof,2025-07-29T17:02:25.641000,Gorilla Glass,6.67''1080x2400p,NaN,"SIM1: Nano, SIM2: Nano","Dual SIM, GSM+GSM","HSPA, LTE",NaN,NaN,"Capacitive Touchscreen, Multi-touch","Mass storage device, USB charging",Yes,USB Type-C 2.0,Funtouch 15,"1080p@30fps, gyro-EIS",Yes,Water resistant (up to 1.5m for 30 min),NaN,NaN,Wi-Fi 5 (802.11 a/b/g/n/ac) 5GHz
3,Infinix,Hot 60 Pro Plus (256GB),Smartphone,25 July 2025,Available,64 bit,20:9,3.5 mm,Li-Po 5160mAh,v5.4,4500 nits,Mediatek Helio G200,"Sleek Black, Titanium Silver, Coral Tides, Mis...",Octa-core (2x2.2 GHz Cortex-A76 & 6x2.0 GHz Co...,8 Cores,https://www.mobiledokan.com/mobile/infinix-hot...,AMOLED,Available,NaN,6 nm,Yes,"Accelerometer, proximity, compass",Available,Yes with A-GPS,Mali-G57 MC2 (1.1GHz),164 mm,https://www.mobiledokan.com/media/infinix-hot-...,256GB,IP65,Yes,"2G, 3G, 4G",Punch-hole,Android v15,v15,440 ppi,"23,999",NaN,"July 25, 2025","[{'variant': '8GB+256GB', 'price': '23,999'}, ...",50MP,"45W wired, 50% in 22 min",8GB,NaN,144 Hz,"50 MP, Wide Angle, Primary Camera",Dust proof,2025-07-29T17:02:26.728739,Corning Gorilla Glass 7i,6.78''1224x2720p,89.3%,"SIM1: Nano, SIM2: Nano","Dual SIM, GSM+GSM","HSPA, LTE",UFS 2.2,6 mm,"Capacitive Touchscreen, Multi-touch","Mass storage device, USB charging",Yes,USB Type-C 2.0,XOS 15.1,"1440p@30fps, 1080p@30/60fps",Yes,Splash proof,155 grams,75.8 mm,Wi-Fi 5 (802.11 a/b/g/n/ac) 5GHz
4,Realme,Note 70T,Smartphone,Exp. 31 July 2025,Upcoming,64 bit,20:9,3.5 mm,Li-Po 6000mAh,v5.4,NaN,Unisoc T7250,"Gold, Black",Octa-core (2x1.8 GHz Cortex-A75 & 6x1.6 GHz Co...,8 Cores,https://www.mobiledokan.com/mobile/realme-note...,IPS LCD,Available,NaN,12 nm,Yes,"Accelerometer, proximity, compass",Available,"Yes with A-GPS, Glonass",Mali-G57 MP1,167.2 mm,https://www.mobiledokan.com/media/realme-note-...,128GB,IP54,Yes,"2G, 3G, 4G",Punch-hole,Android v15,v15,260 ppi,NaN,NaN,"July 24, 2025",[],50+13MP,15W wired,4GB,NaN,90 Hz,"50 MP, f/2.2, Wide Angle, Primary Camera, 13 M...",Dust proof,2025-07-29T17:02:27.622402,Panda Glass,6.74''720x1600p,85.6%,"SIM1: Nano, SIM2: Nano","Dual SIM, GSM+GSM","HSPA, LTE",NaN,7.9 mm,"Capacitive Touchscreen, Multi-touch","Mass storage device, USB charging",Yes,USB Type-C 2.0,Realme UI 5.0,1080p@30fps,Yes,Splash proof,201 grams,76.6 mm,Wi-Fi 5 (802.11 a/b/g/n/ac) 5GHz
5,Motorola,Moto G96 (256GB),Smartphone,16 July 2025,Available,64 bit,20:9,USB Type-C,Li-Po 5500mAh,v5.2,1600 nits,Qualcomm SM7435-AB Snapdragon 7s Gen 2,"Pantone Greener Pastures, Pantone Cattleya Orc...",Octa-core (4x2.40 GHz Cortex-A78 & 4x1.95 GHz ...,8 Cores,https://www.mobiledokan.com/mobile/motorola-mo...,P-OLED,Available,NaN,4 nm,Yes,"Accelerometer, gyro, proximity, compass",Available,"Yes with A-GPS, Glonass",Adreno 710,161.9 mm,https://www.mobiledokan.com/media/motorola-mot...,256GB,IP68,Yes,"2G, 3G, 4G, 5G",Punch-hole,Android v15,v15,395 ppi,NaN,"30,000","July 24, 2025","[{'variant': '256GB', 'price': '30,000'}, {'va...",50+8MP,30W wired,8GB,LPDDR4X,144 Hz,"32 MP, f/2.2, Wide Angle, Primary Camera",Dust proof,2025-07-29T17:02:28.811880,Corning Gorilla Glass v5,6.67''1080x2400p,90.5%,"SIM1: Nano, SIM2: Nano","Dual SIM, GSM+GSM","HSPA, LTE, 5G",UFS 2.2,7.9 mm,"Capacitive Touchscreen, Multi-touch","Mass storage device, USB charging",Yes,USB Type-C 2.0,NaN,"4K@30fps, 1080p@30/60/120fps, gyro-EIS, OIS",Yes,Water resistant (up to 1.5m for 30 min),178 grams,73.3 mm,Wi-Fi 5 (802.11 a/b/g/n/ac) 5GHz
6,Samsung,Galaxy F36,Smartphone,Exp. 29 July 2025,Upcoming,64 bit,19.5:9,USB Type-C,Li-Po 5000mAh,v5.3,NaN,Exynos 1380,"Luxe Violet, Coral Red, Onyx Black",Octa-core (4x2.4 GHz Cortex-A78 & 4x2.0 GHz Co...,8 Cores,https://www.mobiledokan.com/mobile/samsung-gal...,Super AMOLED,Available,NaN,5 nm,Yes,"Accelerometer, gyro, compass",Available,"Yes with A-GPS, Glonass",Mali-G68 MP5,164.4 mm,https://www.mobiledokan.com/media/samsung-gala...,128GB,NaN,Yes,"2G, 3G, 4G, 5G",Punch-hole,Android v15,v15,385 ppi,NaN,NaN,"July 22, 2025",[],50+8+2MP,25W wired,6GB,NaN,120 Hz,"50 MP, f/1.8, Wide Angle, Primary Camera, 8 MP...",NaN,2025-07-29T17:02:30.171489,Corning Gorilla Glass Victus Plus,6.7''1080x2340p,86.0%,"SIM1: Nano, SIM2: Nano","Dual SIM, GSM+GSM","HSPA, LTE, 5G",NaN,7.7 mm,"Capacitive Touchscreen, Multi-touch","Mass storage device, USB charging",Yes,USB Type-C 2.0,One UI 7,"4K@30fps, 1080p@30/60fps, 720p@480fps, gyro-EIS",Yes,NaN,197 grams,77.9 mm,"Wi-Fi 6 (802.11 a/b/g/n/ac/ax) 5GHz, MIMO"
7,Oppo,K13 Turbo Pro,Smartphone,25 July 2025,Available,64 bit,19.5:9,USB Type-C,Li-Po 7000mAh,v5.4,1600 nits,Qualcomm SM8735 Snapdragon 8s Gen 4,"Black Warrior, Purple No. 1, Knight Silver",Octa-core (1x3.21 GHz Cortex-X4 & 3x3.0 GHz Co...,8 Cores,https://www.mobiledokan.com/mobile/oppo-k13-tu...,AMOLED,Available,NaN,4 nm,Yes,"Accelerometer, gyro, proximity, compass",Available,"Yes with A-GPS, Glonass",Adreno 825,162.8 mm,https://www.mobiledokan.com/media/oppo-k13-tur...,256GB,IP68/IP69,Yes,"2G, 3G, 4G, 5G",Punch-hole,Android v15,v15,453 ppi,NaN,"46,000","July 28, 2025","[{'variant': '12GB+256GB CN', 'price': '46,000...",50+2MP,"80W wired, 13.5W PD, 44W UFCS, 33W PPS",12GB,LPDDR5X,120 Hz,"50 MP, f/1.8, Wide Angle, Primary Camera, 2 MP...",Dust proof,2025-07-29T17:02:31.807383,Gorilla Glass,6.8''1280x2800p,89.8%,"SIM1: Nano, SIM2: Nano","Dual SIM, GSM+GSM","HSPA, LTE, 5G",UFS 4.0,7.3 mm,"Capacitive Touchscreen, Multi-touch","Mass storage device, USB charging",Yes,USB Type-C 2.0,ColorOS 15,"4K@30/60fps, 1080p@30fps",Yes,Water resistant (up to 2m for 30 min),208 grams,77.2 mm,"Wi-Fi 7 (802.11 a/b/g/n/ac/be/ax) 5GHz 6GHz, MIMO"
8,Oppo,K13 Turbo,Smartphone,25 July 2025,Available,64 bit,19.5:9,USB Type-C,Li-Po 7000mAh,v5.4,1600 nits,Mediatek Dimensity 8450,"Black Warrior, Purple No. 1, Knight White",Octa-core (1x3.25 GHz Cortex-A725 & 3x3.0 GHz ...,8 Cores,https://www.mobiledokan.com/mobile/oppo-k13-turbo,AMOLED,Available,NaN,4 nm,Yes,"Accelerometer, gyro, proximity, compass",Available,"Yes with A-GPS, Glonass",Mali-G720 MC7,162.8 mm,https://www.mobiledokan.com/media/oppo-k13-tur...,256GB,IP68/IP69,Yes,"2G, 3G, 4G, 5G",Punch-hole,Android v15,v15,453 ppi,NaN,"42,000","July 28, 2025","[{'variant': '12GB+256GB CN', 'price': '42,000...",50+2MP,"80W wired, 13.5W PD, 44W UFCS, 33W PPS",12GB,LPDDR5X,120 Hz,"50 MP, f/1.8, Wide Angle, Primary Camera, 2 MP...",Dust proof,2025-07-29T17:02:32.927855,Gorilla Glass,6.8''1280x2800p,89.8%,"SIM1: Nano, SIM2: Nano","Dual SIM, GSM+GSM","HSPA, LTE, 5G",UFS 3.1,7.3 mm,"Capacitive Touchscreen, Multi-touch","Mass storage device, USB charging",Yes,USB Type-C 2.0,ColorOS 15,"4K@30/60fps, 1080p@30fps",Yes,Water resistant (up to 2m for 30 min),207 grams,77.2 mm,"Wi-Fi 6 (802.11 a/b/g/n/ac/ax) 5GHz, MIMO"
9,Samsung,Galaxy M36,Smartphone,12 July 2025,Available,64 bit,19.5:9,USB Type-C,Li-Ion 5000mAh,v5.3,NaN,Exynos 1380,"Orange Haze, Velvet Black, Serene Green",Octa-core (4x2.4 GHz Cortex-A78 & 4x2.0 GHz Co...,8 Cores,https://www.mobiledokan.com/mobile/samsung-gal...,Super AMOLED,Available,NaN,5 nm,Yes,"Accelerometer, gyro, compass",Available,"Yes with A-GPS, Glonass",Mali-G68 MP5,164.4 mm,https://www.mobiledokan.com/media/samsung-gala...,128GB,NaN,Yes,"2G, 3G, 4G, 5G",Punch-hole,Android v15,v15,385 ppi,NaN,"29,500","July 21, 2025",[],50+8+2MP,25W wired,6GB,LPDDR4X,120 Hz,"50 MP, f/1.8, Wide Angle, Primary Camera, 8 MP...",NaN,2025-07-29T17:02:33.883485,Corning Gorilla Glass Victus Plus,6.7''1080x2340p,86.0%,"SIM1: Nano, SIM2: Nano","Dual SIM, GSM+GSM","HSPA, LTE, 5G",UFS 2.2,7.7 mm,"Capacitive Touchscreen, Multi-touch","Mass storage device, USB charging",Yes,USB Type-C 2.0,One UI 7,"4K@30fps, 1080p@30/60fps, 720p@480fps, gyro-EIS",Yes,NaN,197 grams,77.9 mm,"Wi-Fi 6 (802.11 a/b/g/n/ac/ax) 5GHz, MIMO"

In [12]:
df.device_type.unique()

<ArrowStringArray>
[   'Smartphone', 'Feature phone',    'SmartPhone',  'FeaturePhone',
     'Moto G04s',       'IPS LCD',     'JavaPhone',    'smartphone',
    'Java Phone',       'Symbian',  'Featurephone',             nan]
Length: 12, dtype: str

In [13]:
def fix_device_type(x):
    x = str(x).lower().replace(" ", "")
    if any(brand in x for brand in ['moto', 'galaxy', 'iphone', 'pixel', 'smart']):
        return 'Smart Phone'
    if 'java' in x:
        return 'Java Phone'
    if 'feature' in x:
        return 'Feature Phone'
    if 'smart' in x:
        return 'Smart Phone'
    if 'Symbian' in x:
        return 'Smart Phone'
    return np.nan


df['device_type'] = df['device_type'].apply(fix_device_type)

df.device_type.unique()

<ArrowStringArray>
['Smart Phone', 'Feature Phone', nan, 'Java Phone']
Length: 4, dtype: str

In [14]:
df.head(3)

,brand,model,device_type,release_date,status,architecture,aspect_ratio,audio_jack,battery_capacity,bluetooth,brightness,chipset,colors,cpu,cpu_cores,detail_url,display_type,edge,expandable_memory,fabrication,face_unlock,features,gprs,gps,gpu,height,image_url,internal_storage,ip_rating,loudspeaker,network,notch,operating_system,os_version,pixel_density,price_official,price_unofficial,price_updated,price_variants,primary_camera_resolution,quick_charging,ram,ram_type,refresh_rate,resolution,ruggedness,scraped_at,screen_protection,screen_size,screen_to_body_ratio,sim_size,sim_slot,speed,storage_type,thickness,touch_screen,usb,usb_otg,usb_type_c,user_interface,video,volte,waterproof,weight,width,wlan
0,Oppo,K13 Turbo Pro (512GB),Smart Phone,25 July 2025,Available,64 bit,19.5:9,USB Type-C,Li-Po 7000mAh,v5.4,1600 nits,Qualcomm SM8735 Snapdragon 8s Gen 4,"Black Warrior, Purple No. 1, Knight Silver",Octa-core (1x3.21 GHz Cortex-X4 & 3x3.0 GHz Co...,8 Cores,https://www.mobiledokan.com/mobile/oppo-k13-tu...,AMOLED,Available,NaN,4 nm,Yes,"Accelerometer, gyro, proximity, compass",Available,"Yes with A-GPS, Glonass",Adreno 825,162.8 mm,https://www.mobiledokan.com/media/oppo-k13-tur...,512GB,IP68/IP69,Yes,"2G, 3G, 4G, 5G",Punch-hole,Android v15,v15,453 ppi,NaN,"56,000","July 28, 2025","[{'variant': '12GB+512GB CN', 'price': '56,000...",50+2MP,"80W wired, 13.5W PD, 44W UFCS, 33W PPS",12GB,LPDDR5X,120 Hz,"50 MP, f/1.8, Wide Angle, Primary Camera, 2 MP...",Dust proof,2025-07-29T17:02:23.596376,Gorilla Glass,6.8''1280x2800p,89.8%,"SIM1: Nano, SIM2: Nano","Dual SIM, GSM+GSM","HSPA, LTE, 5G",UFS 4.0,7.3 mm,"Capacitive Touchscreen, Multi-touch","Mass storage device, USB charging",Yes,USB Type-C 2.0,ColorOS 15,"4K@30/60fps, 1080p@30fps",Yes,Water resistant (up to 2m for 30 min),208 grams,77.2 mm,"Wi-Fi 7 (802.11 a/b/g/n/ac/be/ax) 5GHz 6GHz, MIMO"
1,Oppo,K13 Turbo (512GB),Smart Phone,25 July 2025,Available,64 bit,19.5:9,USB Type-C,Li-Po 7000mAh,v5.4,1600 nits,Mediatek Dimensity 8450,"Black Warrior, Purple No. 1, Knight White",Octa-core (1x3.25 GHz Cortex-A725 & 3x3.0 GHz ...,8 Cores,https://www.mobiledokan.com/mobile/oppo-k13-tu...,AMOLED,Available,NaN,4 nm,Yes,"Accelerometer, gyro, proximity, compass",Available,"Yes with A-GPS, Glonass",Mali-G720 MC7,162.8 mm,https://www.mobiledokan.com/media/oppo-k13-tur...,512GB,IP68/IP69,Yes,"2G, 3G, 4G, 5G",Punch-hole,Android v15,v15,453 ppi,NaN,"52,000","July 28, 2025","[{'variant': '12GB+512GB CN', 'price': '52,000...",50+2MP,"80W wired, 13.5W PD, 44W UFCS, 33W PPS",12GB,LPDDR5X,120 Hz,"50 MP, f/1.8, Wide Angle, Primary Camera, 2 MP...",Dust proof,2025-07-29T17:02:24.734934,Gorilla Glass,6.8''1280x2800p,89.8%,"SIM1: Nano, SIM2: Nano","Dual SIM, GSM+GSM","HSPA, LTE, 5G",UFS 3.1,7.3 mm,"Capacitive Touchscreen, Multi-touch","Mass storage device, USB charging",Yes,USB Type-C 2.0,ColorOS 15,"4K@30/60fps, 1080p@30fps",Yes,Water resistant (up to 2m for 30 min),207 grams,77.2 mm,"Wi-Fi 6 (802.11 a/b/g/n/ac/ax) 5GHz, MIMO"
2,Vivo,Y400,Smart Phone,Not announced yet,Rumored,64 bit,NaN,USB Type-C,Li-Po 6000mAh,v5.0,NaN,Qualcomm SM6225 Snapdragon 685,Green; other colors,Octa-core (2x2.2 GHz Cortex-A78 & 6x1.95 GHz C...,8 Cores,https://www.mobiledokan.com/mobile/vivo-y400,AMOLED,Available,NaN,6 nm,Yes,"Accelerometer, gyro, proximity, compass",Available,"Yes with A-GPS, Glonass",Adreno 613,NaN,https://www.mobiledokan.com/media/vivo-y400-gr...,128GB,IP68/IP69,Yes,"2G, 3G, 4G",Punch-hole,Android v15,v15,NaN,NaN,NaN,"July 27, 2025",[],50+2MP,44W wired,8GB,NaN,120 Hz,"50 MP, f/1.8, Wide Angle, Primary Camera, 2 MP...",Dust proof,2025-07-29T17:02:25.641000,Gorilla Glass,6.67''1080x2400p,NaN,"SIM1: Nano, SIM2: Nano","Dual SIM, GSM+GSM","HSPA, LTE",NaN,NaN,"Capacitive Touchscreen, Multi-touch","Mass storage device, USB charging",Yes,USB Type-C 2.0,Funtouch 15,"1080p@30fps, gyro-EIS",Yes,Water resistant (up to 1.5m for 30 min),NaN,NaN,Wi-Fi 5 (802.11 a/b/g/n/ac) 5GHz

creating function to convert string to number and other ram storage into one UNIT and battery power into simple unit

In [15]:
# convert into number
def into_number(column, pattern= r"([\d.]+)"):
    text = column.astype(str).str.replace("," , "", regex=False)
    return pd.to_numeric(text.str.extract(pattern)[0], errors="coerce")

# for ram gb tb pb , converting into gb
def to_gb(col):
    n = into_number(col)
    n = n.where(~col.str.contains("MB", na=False), n/1024)
    n = n.where(~col.str.contains("TB", na=False), n* 1024)
    return n

import re
def max_watt(text):
    if not isinstance(text, str):
        return np.nan
    w = re.findall(r"(\d+(?:\.\d+)?)\s*W", text)
    return max(map(float, w)) if w else np.nan

In [16]:
df['price_official'].head(4)

0       NaN
1       NaN
2       NaN
3    23,999
Name: price_official, dtype: str

In [17]:
# changing currency

rate = 0.77 

for old, new in [('price_official', 'official_inr'), ('price_unofficial','unofficial_inr')]:
    df[new] = pd.to_numeric(df[old].str.replace(r"[^\d.]", "", regex=True), errors= "coerce") *rate
df['price'] = df['official_inr'].fillna(df['unofficial_inr'])
df['price'].head(4)

0    43120.00
1    40040.00
2         NaN
3    18479.23
Name: price, dtype: float64

In [18]:
# adding new column year

df['year']= pd.to_numeric(df['release_date'].str.extract(r"\b((?:19|20)\d{2})\b")[0], errors="coerce")
print(df['year'].isna().sum())
df['year'].head(4)

68

0    2025.0
1    2025.0
2       NaN
3    2025.0
Name: year, dtype: float64

In [19]:
df.loc[df['year'] > 2026, 'year'] = 2017

In [24]:
df.ram.head(4)

0    12GB
1    12GB
2     8GB
3     8GB
Name: ram, dtype: str

In [25]:
print(df['ram'].head(4))
df['ram'] = to_gb(df['ram'])
df['ram'].head(4)

0    12GB
1    12GB
2     8GB
3     8GB
Name: ram, dtype: str

0    12.0
1    12.0
2     8.0
3     8.0
Name: ram, dtype: float64

In [26]:
df['internal_storage'].head(20)

0     512GB
1     512GB
2     128GB
3     256GB
4     128GB
5     256GB
6     128GB
7     256GB
8     256GB
9     128GB
10    128GB
11    256GB
12    128GB
13    128GB
14      1TB
15    512GB
16     64GB
17    128GB
18    128GB
19    128GB
Name: internal_storage, dtype: str

In [27]:
df['storage'] = to_gb(df['internal_storage'])
df.storage.head(20)

0      512.0
1      512.0
2      128.0
3      256.0
4      128.0
5      256.0
6      128.0
7      256.0
8      256.0
9      128.0
10     128.0
11     256.0
12     128.0
13     128.0
14    1024.0
15     512.0
16      64.0
17     128.0
18     128.0
19     128.0
Name: storage, dtype: float64

In [29]:
df.battery_capacity.head(10)

0     Li-Po 7000mAh
1     Li-Po 7000mAh
2     Li-Po 6000mAh
3     Li-Po 5160mAh
4     Li-Po 6000mAh
5     Li-Po 5500mAh
6     Li-Po 5000mAh
7     Li-Po 7000mAh
8     Li-Po 7000mAh
9    Li-Ion 5000mAh
Name: battery_capacity, dtype: str

In [30]:
df['battery'] = pd.to_numeric(df['battery_capacity'].str.extract(r"(\d{3,6})\s*mAh")[0], errors='coerce')
df.battery.head(10)

0    7000.0
1    7000.0
2    6000.0
3    5160.0
4    6000.0
5    5500.0
6    5000.0
7    7000.0
8    7000.0
9    5000.0
Name: battery, dtype: float64